name: Sort IPs with Python

# 允许手动触发和推送触发
on:
  push:  # 推送代码时自动触发
    paths:
      - '4.txt'
      - '6.txt'
  workflow_dispatch:  # 手动触发
    inputs:
      manualTrigger:
        description: 'Manual Trigger'
        required: false
        default: 'true'

jobs:
  sort-ips:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出代码

      - name: Set up Python
        uses: actions/setup-python@v4  # 设置Python环境
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script to sort IPs
        run: |
          python sort_ips.py

      - name: Upload sorted and formatted files
        uses: actions/upload-artifact@v4  # 上传处理后的文件
        with:
          name: sorted_ips
          path: |
            ipv4.txt
            ipv6.txt
